### ISSUE TITLE
若将图片拖拽至地址栏仍可保存

### ISSUE THREAD

**Issue by df7c5117** [CRH380A-2722/jQuery-picopyright#13]
记得可以用`<img ondragstart="return false"/>`或者`<img draggable="false" />`解决

**Comment by CRH380A-2722** [comment]
可以为图片增设CSS: 
``` CSS
img {
    pointer-events: none;
}
```
我记得jQuery可以动态添加CSS的，回去修改一下就好了（
