### ISSUE TITLE
发现在CM12.1以及iOS9的浏览器上该插件无效

### ISSUE THREAD

**Issue by df7c5117** [CRH380A-2722/jQuery-picopyright#16]
如图
![737499321298044762](https://cloud.githubusercontent.com/assets/13192856/22623583/030af588-eb9b-11e6-9396-5a987d503ab1.jpg)
![qq 20170205115907](https://cloud.githubusercontent.com/assets/13192856/22623584/030ef6e2-eb9b-11e6-9175-6e157424b0bc.png)

在桌面端chrome 55功能正常

**Comment by CRH380A-2722** [comment]
这就尴尬了，我测试的时候都是在Chrome环境上。。

我去其它浏览器测试下，看看有没有其它的解决办法

**Comment by CRH380A-2722** [comment]
我加了这段代码
``` CSS
img {
  webkit-touch-callout: none;
  -ms-touch-callout: none;
  -moz-touch-callout: none;
  -o-touch-callout: none;
  touch-callout: none;
}
```
在iOS浏览器上测试后没有问题
